### ISSUE TITLE
terraform-provider-esxi_v1.10.2 plugin crashed!

### ISSUE THREAD

**Issue by n1603** [josenk/terraform-provider-esxi#169]
**Describe the bug**
while trying to create VM from ova, terraform-provider-esxi plugin is crasing

**To Reproduce**
use the example from the project and update the ova file path to local file system.

**Expected behavior**
VM created from OVA. 

**Terraform log**
`esxi_guest-test-1: Creating...
╷
│ Error: Request cancelled
│
│   with esxi_guest.rainier-test-1,
│   on main.tf line 10, in resource "esxi_guest" "rainier-test-1":
│   10: resource "esxi_guest" "rainier-test-1" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-esxi_v1.10.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcc3cce]

goroutine 36 [running]:
github.com/josenk/terraform-provider-esxi/esxi.guestCREATE(0xc0001d5ea0, 0xc00020e520, 0xe, 0xc00021a1f8, 0x13, 0xc0002301e0, 0x60, 0x1492fb8, 0x1, 0x0, ...)
	github.com/josenk/terraform-provider-esxi/esxi/guest-create.go:212 +0x1eae
github.com/josenk/terraform-provider-esxi/esxi.resourceGUESTCreate(0xc00047c690, 0xd96900, 0xc0001d5ea0, 0x2, 0x152de40)
	github.com/josenk/terraform-provider-esxi/esxi/resource_guest.go:403 +0x1ace
github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0001aea80, 0xc000218be0, 0xc000046a40, 0xd96900, 0xc0001d5ea0, 0xda4f01, 0xc0000b6fd8, 0xc00024c1b0)
	github.com/hashicorp/terraform@v0.12.2/helper/schema/resource.go:286 +0x375
github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0001aed80, 0xc0003898d8, 0xc000218be0, 0xc000046a40, 0xc000243dc8, 0xc000222100, 0xda6f20)
	github.com/hashicorp/terraform@v0.12.2/helper/schema/provider.go:285 +0x99
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000aea28, 0x101a310, 0xc0002219e0, 0xc00022c3c0, 0xc0000aea28, 0xc0002219e0, 0xc000011a50)
	github.com/hashicorp/terraform@v0.12.2/helper/plugin/grpc_provider.go:851 +0x88b
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xe7bc20, 0xc0000aea28, 0x101a310, 0xc0002219e0, 0xc000218910, 0x0, 0x101a310, 0xc0002219e0, 0xc00023a900, 0x45a)
	github.com/hashicorp/terraform@v0.12.2/internal/tfplugin5/tfplugin5.pb.go:3217 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001680, 0x1021f18, 0xc000102c00, 0xc00022e100, 0xc000280420, 0x14ef2a0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.18.0/server.go:966 +0x486
google.golang.org/grpc.(*Server).handleStream(0xc000001680, 0x1021f18, 0xc000102c00, 0xc00022e100, 0x0)
	google.golang.org/grpc@v1.18.0/server.go:1245 +0xcbd
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000381e0, 0xc000001680, 0x1021f18, 0xc000102c00, 0xc00022e100)
	google.golang.org/grpc@v1.18.0/server.go:685 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.18.0/server.go:683 +0xa5

Error: The terraform-provider-esxi_v1.10.2 plugin crashed!`
**Desktop (please complete the following information):**
 - OS:  Centos7
 - Terraform Version: Terraform v1.1.5
 - Ovftool Version: 
 - This Plugin Version : 1.10.2

**Comment by n1603** [comment]
That turned out to be my local issue. closing it.
